#! /bin/bash

CWD=$(pwd)
DIR="$(dirname "$(readlink -f "$0")")"

setup () {
  cp -r ${DIR}/../../data ${CWD}/
  cp -r ${DIR}/../../configuration ${CWD}/

  cp ${DIR}/LICENSE ${CWD}/
  cp ${DIR}/.editorconfig ${CWD}/
  cp ${DIR}/.travis.yml ${CWD}/
  cp ${DIR}/gitignore.template ${CWD}/.gitignore
  cp ${DIR}/package.json ${CWD}/package.json
  cp ${DIR}/README.md ${CWD}/

  echo "What is the name of your comparison?"
  read -e NAME
  if [[ ${NAME} == "" ]]; then
      NAME="ultimate-comparison-project"
  fi
  echo "What is the version of your comparison?"
  read -e VERS
  if [[ ${VERS} == "" ]]; then
      VERS="0.0.0"
  fi
  echo "How would you describe your comparison?"
  read -e DESC
  sed -i "s/##name/${NAME}/" ${CWD}/package.json
  sed -i "s/##description/${VERS}/" ${CWD}/package.json
  sed -i "s/##version/${DESC}/" ${CWD}/package.json
  npm install
  npm i ultimate-comparison@next
}

start () {
  npm start
}

dev () {
  npm run dev
}

if [[ "$1" != "setup" ]] &&  [[ "$1" != "start" ]] &&  [[ "$1" != "dev" ]]; then
    echo "Invalid command, please use 'uc setup' or 'uc start' or 'uc dev"
else
    eval ${1}
fi
