#! /bin/bash

CWD=$(pwd)
DIR="$(dirname "$(readlink -f "$0")")"

setup () {
  cp -r ${DIR}/../../data ${CWD}/
  cp -r ${DIR}/../../configuration ${CWD}/

  cp ${DIR}/.editorconfig ${CWD}/
  cp ${DIR}/.travis.yml ${CWD}/
  cp ${DIR}/gitignore.template ${CWD}/.gitignore
  cp ${DIR}/package.json ${CWD}/package.json
  cp ${DIR}/README.md ${CWD}/
  cp ${DIR}/webpack.config.babel.js ${CWD}/

  cp ${DIR}/../../tsconfig.json ${CWD}/

  echo "What is the name of your comparison?"
  read -e NAME
  if [[ ${NAME} == "" ]]; then
      NAME="ultimate-comparison-project"
  fi
  echo "What is the version of your comparison?"
  read -e VERS
  if [[ ${VERS} == "" ]]; then
      VERS="0.0.0"
  fi
  echo "How would you describe your comparison?"
  read -e DESC
  sed -i "s/##asdfn/${NAME}/" ${CWD}/package.json
  sed -i "s/##asdfv/${VERS}/" ${CWD}/package.json
  sed -i "s/##asdfd/${DESC}/" ${CWD}/package.json
  npm install
}

start () {
  npm start
}

if [[ "$1" != "setup" ]] &&  [[ "$1" != "start" ]]; then
    echo "Invalid command, please use 'uc setup' or 'uc start'"
else
    eval ${1}
fi
